Fix 'Usage' line to use new COMMAND SCRIPT syntax. Error message if tovid-init not found.

diff --git a/tovid/src/makevcd b/tovid/src/makevcd
--- a/tovid/src/makevcd
+++ b/tovid/src/makevcd
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 ME="[makevcd]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run makevcd as:\ntovid vcd OPTIONS"
+exit 1 ; }
 
 # makevcd
 # Part of the tovid suite
@@ -39,7 +44,7 @@ $TOVID_HOME_PAGE
 EOF`
 
 USAGE=`cat << EOF
-Usage: makevcd [OPTIONS] {VCDIMAGER.xml}
+Usage: tovid vcd [OPTIONS] {VCDIMAGER.xml}
 
 Where OPTIONS may be any of the following:
 
