Fix 'Usage' line to use new COMMAND SCRIPT syntax. Error message if tovid-init not found.

diff --git a/tovid/src/makemenu b/tovid/src/makemenu
--- a/tovid/src/makemenu
+++ b/tovid/src/makemenu
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 ME="[makemenu]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run makemenu as:\ntovid menu OPTIONS"
+exit 1 ; }
 
 # version $Id$
 # makemenu
diff --git a/tovid/src/makempg b/tovid/src/makempg
--- a/tovid/src/makempg
+++ b/tovid/src/makempg
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 ME="[tovid]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run makempg as:\ntovid mpg OPTIONS"
+exit 1 ; }
 
 # tovid
 # Part of the tovid suite
@@ -52,7 +57,7 @@ $TOVID_HOME_PAGE
 EOF`
 
 USAGE=`cat << EOF
-Usage: tovid [OPTIONS] -in {input file} -out {output prefix}
+Usage: tovid mpg [OPTIONS] -in {input file} -out {output prefix}
 
 Common options:
 
diff --git a/tovid/src/makexml b/tovid/src/makexml
--- a/tovid/src/makexml
+++ b/tovid/src/makexml
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 ME="[makexml]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run makexml as:\ntovid xml OPTIONS"
+exit 1 ; }
 
 # makexml
 # Part of the tovid suite
@@ -44,7 +49,7 @@ $TOVID_HOME_PAGE
 EOF`
 
 USAGE=`cat << EOF
-Usage:  makexml [OPTIONS] {video1.mpg video2.mpg ...} -out OUT_PREFIX
+Usage:  tovid xml [OPTIONS] {video1.mpg video2.mpg ...} -out OUT_PREFIX
 
 Common OPTIONS:
 
diff --git a/tovid/src/tovid-batch b/tovid/src/tovid-batch
--- a/tovid/src/tovid-batch
+++ b/tovid/src/tovid-batch
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 ME="[tovid-batch]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run tovid-batch as:\ntovid batch OPTIONS"
+exit 1 ; }
 
 # tovid-batch
 # Part of the tovid suite
@@ -38,7 +43,7 @@ $TOVID_HOME_PAGE
 EOF`
 
 USAGE=`cat << EOF
-Usage: tovid-batch [OPTIONS] -infiles <input files>
+Usage: tovid batch [OPTIONS] -infiles <input files>
 
 OPTIONS may be any options that tovid accepts. See 'man tovid'.
 
diff --git a/tovid/src/tovid-interactive b/tovid/src/tovid-interactive
--- a/tovid/src/tovid-interactive
+++ b/tovid/src/tovid-interactive
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 ME="[tovid-interactive]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run tovid-interactive as:\ntovid interactive OPTIONS"
+exit 1 ; }
 
 # tovid-interactive
 # Part of the tovid suite
