major cleanup; removed .iso stuff; authoring from dvd directory

diff --git a/tovid/src/makedvd b/tovid/src/makedvd
--- a/tovid/src/makedvd
+++ b/tovid/src/makedvd
@@ -41,20 +41,21 @@ $TOVID_HOME_PAGE
 EOF`
 
 USAGE=`cat << EOF
-Usage: makedvd [OPTIONS] {FILE.xml}
+Usage: makedvd [OPTIONS] FILE.xml
+   or: makedvd [OPTIONS] DVD_DIR
 
-Where OPTIONS may be any of the following:
+With FILE.xml, containing dvdauthor XML as generated by 'makexml',
+or DVD_DIR, a directory containing a DVD filesystem (VIDEO_TS, namely).
 
-  -author              create DVD filesystem
-  -image               create DVD iso
-  -burn                burn filesystem or iso
-  -device DEVFS_NAME   (default /dev/dvd)
-  -speed NUM           (default automatic)
-  -label DISC_LABEL    (default is FOO from dest="foo" in xml)
+OPTIONS may be any of the following:
 
-FILE.xml should contain dvdauthor-style XML, as generated by 'makexml'.
+  -author              Create DVD filesystem from FILE.xml
+  -burn                Burn DVD filesystem from DVD_DIR
+  -device DEVFS_NAME   DVD recorder device name (Default: /dev/dvdrw)
+  -speed NUM           Burn speed (Default: automatic)
+  -label DISC_LABEL    Disc label (Default: base name of FILE)
+
 See the makedvd manual page ('man makedvd') for additional documentation.
-
 EOF`
 
 # Print script name, usage notes, and optional error message, then exit.
@@ -75,7 +76,7 @@ runtime_error ()
     echo "makedvd encountered an error during the DVD creation process:"
     echo "$@"
     echo "See if anything in the above output helps you diagnose the"
-    echo "problem, and please file a bug report at tovid.org (_not_i" 
+    echo "problem, and please file a bug report at tovid.org (_not_"
     echo "the dvdauthor list) containing the above output."
     echo "Sorry for the inconvenience!"
     echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
@@ -85,8 +86,6 @@ runtime_error ()
 # Defaults
 # Create the DVD filesystem hierarchy?
 DO_AUTHOR=false
-# Create an ISO image?
-DO_IMAGE=false
 # Burn the image to disc?
 DO_BURN=false
 
@@ -131,13 +130,12 @@ echo $"$SCRIPTNAME"
 assert_dep_group "dvd" "You are missing dependencies required for burning DVDs!"
 
 if test $# -lt 1; then
-    usage_error "Please provide the name of a dvdauthor .xml file to author."
+    usage_error "Please provide a filename (.xml, or dvd filesystem folder)"
 fi
 
 while test $# -gt 1; do
     case "$1" in
         "-author" ) DO_AUTHOR=: ;;
-        "-image" )  DO_IMAGE=: ;;
         "-burn" )   DO_BURN=: ;;
         "-device" )
             # Get device name
@@ -161,36 +159,92 @@ while test $# -gt 1; do
     shift
 done
 
-DVDAUTHOR_XML="$1"
+DISC_NAME=`abspath "$1"`
 
-# Make sure the file exists
-if test ! -f "$DVDAUTHOR_XML"; then
-    echo "Could not open file: $DVDAUTHOR_XML"
-    exit 1
-else
-    echo "Authoring disc from file: $DVDAUTHOR_XML"
+# See what kind of file we're working with, and do the right thing
+# Author an XML file
+if echo "$DISC_NAME" | grep -q -i '\.xml$'; then
+    DVDAUTHOR_XML="$DISC_NAME"
+    DO_AUTHOR=:
+# Burn a directory containing a VIDEO_TS subfolder
+elif test -d "$DISC_NAME"; then
+    if test -d "$DISC_NAME/VIDEO_TS"; then
+        DO_BURN=:
+        OUT_DIR="$DISC_NAME"
+    fi
 fi
 
-# Set disc title and output directory based on XML filename
+# Set disc title and output directory based on given filename
 # (without .xml, space to underscore)
-test -z $DISC_LABEL && DISC_LABEL=$( basename "$DVDAUTHOR_XML" ".xml" | tr ' ' '_')
+test -z $DISC_LABEL && DISC_LABEL=$( basename "$DISC_NAME" ".xml" | tr ' ' '_')
 # And, just in case that failed...
 test -z $DISC_LABEL && DISC_LABEL="UNTITLED_DVD"
-OUT_DIR=`grep 'dest=' $DVDAUTHOR_XML | cut -d= -f2 | tr -d '">'`
 
-# Extract a valid volume ID
-VOLID=`echo "$DISC_LABEL" | tr a-z A-Z`
-# Make sure we have a valid VOLID at this point...can't be too long
-VALID_VOLID=`echo $VOLID | awk '{ print substr($0, 0, 32) }'`
-if test $VOLID != $VALID_VOLID; then
-    echo "Disk label is too long. Truncating to $VALID_VOLID"
-    VOLID=$VALID_VOLID
-else
-    echo "Using disk label \"$VOLID\""
+# Authoring
+if $DO_AUTHOR; then
+    # Make sure the XML file exists
+    if test ! -f "$DVDAUTHOR_XML"; then
+        echo "Could not open file: $DVDAUTHOR_XML"
+        exit 1
+    else
+        echo "Authoring disc from file: $DVDAUTHOR_XML"
+    fi
+
+    # The dest= argument from the XML file will be the output directory
+    OUT_DIR=`grep 'dest=' $DVDAUTHOR_XML | cut -d= -f2 | tr -d '">'`
+
+    # Determine how much space will be needed for authoring, by adding up
+    # the sizes of all .vobs in the XML file.
+    NUM_VOBS=`grep vob "$DVDAUTHOR_XML" | wc -l`
+    VOB_LIST=`grep vob "$DVDAUTHOR_XML" | awk -F '"' '{ print $2 }' | tr '\n' ':'`
+    i=1
+    DISC_SUM=0
+    while test $i -le $NUM_VOBS; do
+      VOB=`echo "$VOB_LIST" | awk -F ':' '{ print $'$i' }'`
+      VOB_SIZE=`du -B M "$VOB" | awk -F ' ' '{print $1}' | tr -d M`
+      DISC_SUM=`expr $VOB_SIZE \+ $DISC_SUM`
+      i=`expr $i \+ 1`
+    done
+    AVAIL_SPACE=`df -B M -P . | awk 'NR != 1 {print $4;}' | tr -d M`
+
+    if test $DISC_SUM -gt $AVAIL_SPACE; then
+       echo $SEPARATOR
+       precho "Cannot continue! ${DISC_SUM}MB needed, but only ${AVAIL_SPACE}MB in `pwd`"
+       echo "Exiting..."
+       exit 1
+    fi
+    if test $DISC_SUM -gt $DVD_SIZE_MB; then
+       echo $SEPARATOR
+       echo "Warning! Making a DVD image larger than a standard single-sided DVD."
+       echo "Current DVD image is ${DISC_SUM}MB."
+    fi
+
+    # Create disc structure
+    DVDAUTHOR_CMD="dvdauthor -x \"$DVDAUTHOR_XML\""
+    echo $SEPARATOR
+    echo "Authoring DVD-Video disc structure, estimated to require ${DISC_SUM}MB."
+    echo "Creating disc structure with the following command:"
+    echo $DVDAUTHOR_CMD
+    echo $SEPARATOR
+    
+    if eval "$DVDAUTHOR_CMD" 2>&1; then
+        echo $SEPARATOR
+        echo "Disc structure successfully created in directory: $OUT_DIR."
+    else
+        runtime_error "Could not create the DVD-Video disc structure in $OUT_DIR. Leaving $OUT_DIR for inspection."
+    fi
 fi
 
-# Remind user to insert a DVD, check for DVD device
-if $DO_BURN; then
+echo "Authoring completed."
+
+# If not burning, print a message and exit
+if ! $DO_BURN; then
+    echo "You can burn the disc with a command like this:"
+    echo "  $ makedvd -burn $OUT_DIR"
+
+# Otherwise, get on with burning
+else
+    # Remind user to insert a DVD, check for DVD device
     echo $SEPARATOR
     echo "Please insert a blank DVD+/-R(W) disc into your DVD-recorder"
     echo "($DVDRW_DEVICE) if you have not already done so."
@@ -204,116 +258,6 @@ if $DO_BURN; then
       echo "Couldn't find $DVDRW_DEVICE! Stopping here."
       exit 1
     fi
-fi
-
-# An existing target directory may be due to a prior attempt at encoding.
-# If -author was specified, overwrite it.
-if test -d $OUT_DIR; then
-   echo $SEPARATOR   
-   echo "Authoring directory $OUT_DIR already exists."
-
-   if $DO_AUTHOR; then
-      echo "Deleting contents of directory: $OUT_DIR"
-      rm -rf "$OUT_DIR"
-   else
-      echo "Skipping authoring; to force, use the -author option."
-   fi
-   
-# If there's no target directory, but there's an .iso image and the user
-# doesn't want to DO_IMAGE, then s/he probably wants to burn it. 
-# No need to author.
-elif test ! -d $OUT_DIR && test -s $DISC_LABEL.iso && ! $DO_IMAGE; then :
-
-# No existing target directory, and no existing .iso (or the user wants
-# to remake an existing iso without having an existing target directory).
-# Need to author.
-else
-   DO_AUTHOR=:
-fi
-
-# See if target disc image exists, if -image was supplied overwrite it
-if test -s $DISC_LABEL.iso; then
-   echo $SEPARATOR
-   echo "Disc image $DISC_LABEL.iso already exists."
-
-   if $DO_IMAGE; then 
-      echo "Removing existing image: $DISC_LABEL.iso"
-      rm -f $DISC_LABEL.iso
-   else
-      echo "Skipping image (.iso) creation; To force, use the -image option."
-   fi
-fi
-
-# Warn if there isn't enough space to make the image
-# Get the vobs in the xml file. Use ':' as field separator so that filenames can 
-# have spaces.
-NUM_VOBS=`grep vob "$DVDAUTHOR_XML" | wc -l`
-VOB_LIST=`grep vob "$DVDAUTHOR_XML" | awk -F '"' '{ print $2 }' | tr '\n' ':'`
-
-i=1
-DISC_SUM=0
-while test $i -le $NUM_VOBS; do
-  VOB=`echo "$VOB_LIST" | awk -F ':' '{ print $'$i' }'`
-  VOB_SIZE=`du -B M "$VOB" | awk -F ' ' '{print $1}' | tr -d M`
-  DISC_SUM=`expr $VOB_SIZE \+ $DISC_SUM`
-  i=`expr $i \+ 1`
-done
-
-AVAIL_SPACE=`df -B M -P . | awk 'NR != 1 {print $4;}' | tr -d M`
-
-NEEDED_SPACE=0
-$DO_AUTHOR && NEEDED_SPACE=`expr $NEEDED_SPACE \+ $DISC_SUM`
-$DO_IMAGE && NEEDED_SPACE=`expr $NEEDED_SPACE \+ $DISC_SUM`
-
-if test $NEEDED_SPACE -gt $AVAIL_SPACE; then
-   echo $SEPARATOR
-   precho "Cannot continue! ${NEEDED_SPACE}MB needed, but only ${AVAIL_SPACE}MB in `pwd`"
-   echo "Exiting..."
-   exit 1
-fi
-
-if test $DISC_SUM -gt $DVD_SIZE_MB; then
-   echo $SEPARATOR
-   echo "Warning! Making a DVD image larger than a standard single-sided DVD."
-   echo "Current DVD image is ${DISC_SUM}MB."
-fi
-
-if $DO_AUTHOR; then
-    # Create disc structure
-    DVDAUTHOR_CMD="dvdauthor -x \"$DVDAUTHOR_XML\""
-    echo $SEPARATOR
-    echo "Authoring DVD-Video disc structure, estimated to require ${DISC_SUM}MB."
-    echo "Creating disc structure with the following command:"
-    echo $DVDAUTHOR_CMD
-    echo $SEPARATOR
-    
-    if eval "$DVDAUTHOR_CMD" 2>&1; then
-        echo $SEPARATOR
-        echo "Disc structure successfully created in $OUT_DIR."
-    else
-        runtime_error "Could not create the DVD-Video disc structure in $OUT_DIR. Leaving $OUT_DIR for inspection."
-    fi
-fi
-
-if $DO_IMAGE; then
-    # Create ISO image
-    ISO_CMD="mkisofs -quiet -dvd-video -V \"$VOLID\" -o \"$DISC_LABEL.iso\" $OUT_DIR"
-    echo $SEPARATOR
-    echo "Building the DVD filesystem ISO image, estimated to require ${DISC_SUM}MB."
-    echo "Creating the ISO image with the following command:"
-    echo $ISO_CMD
-    echo $SEPARATOR
-
-    if eval "$ISO_CMD" 2>&1; then
-        echo $SEPARATOR
-        echo "ISO image $DISC_LABEL.iso successfully created."
-    else
-        runtime_error "Could not create ISO image $DISC_LABEL.iso"
-    fi
-fi
-
-# Burn the disc, if requested
-if $DO_BURN; then
 
     GROWISOFS_VER=`growisofs -version | grep version | awk '{ print $6 }' | sed 's/,//g'`
 
@@ -326,10 +270,11 @@ if $DO_BURN; then
       until $HAVE_DVD_RW || $HAVE_BLANK_DVD_R
       do
         TIME_SCALE=1
-        # TODO: smarter loop. User feedback (ie "hit any key" [where's the "any" key anyway?]) 
-        # is bad for when makedvd is called from the gui. But, it usually takes 2 cycles for
-        # the dvd player to recognize a new disc. Is there a better interface to it? Waiting
-        # till the drive's LED goes off is good, but how?
+        # TODO: smarter loop. User feedback (ie "hit any key" [where's the "any"
+        # key anyway?]) is bad for when makedvd is called from the gui. But, it
+        # usually takes 2 cycles for the dvd player to recognize a new disc. Is
+        # there a better interface to it? Waiting till the drive's LED goes off
+        # is good, but how?
         echo "Found $DISC_STATUS $DISC_TYPE. Please insert a usable DVD into $DVDRW_DEVICE."
         for COUNTER in 5 4 3 2 1; do
           printf "Trying again in %2s seconds...\r" `expr $COUNTER \* $TIME_SCALE`
@@ -343,6 +288,9 @@ if $DO_BURN; then
 
     echo $SEPARATOR
     echo "Found $DISC_STATUS $DISC_TYPE."
+
+    DISC_SUM=`du -s $OUT_DIR | awk -F ' ' '{print $1}'`
+    DISC_SUM=`echo "$DISC_SUM / 1024 / 1024" | bc`
 
     if test $DISC_SUM -gt $DISC_CAPACITY; then
        echo $SEPARATOR
@@ -362,22 +310,24 @@ if $DO_BURN; then
       echo "Found $DISC_STATUS $DISC_TYPE in $DVDRW_DEVICE. Blanking..."
       dvd+rw-format -blank $DVDRW_DEVICE
     fi
-
-    # If an image was created, burn that
-    if test -s $DISC_LABEL.iso; then
-       BURN_CMD="growisofs -use-the-force-luke=dao -dvd-compat $BURN_SPEED -Z $DVDRW_DEVICE=\"$DISC_LABEL.iso\""
-       BURN_METHOD="ISO to DVD"
-    # or burn from the DVD directory
+    
+    # Extract a valid volume ID
+    VOLID=`echo "$DISC_LABEL" | tr a-z A-Z`
+    # Make sure we have a valid VOLID at this point...can't be too long
+    VALID_VOLID=`echo $VOLID | awk '{ print substr($0, 0, 32) }'`
+    if test $VOLID != $VALID_VOLID; then
+        echo "Disk label is too long. Truncating to $VALID_VOLID"
+        VOLID=$VALID_VOLID
     else
-       BURN_CMD="growisofs -use-the-force-luke=dao -dvd-compat $BURN_SPEED -Z $DVDRW_DEVICE -dvd-video -V \"$VOLID\" $OUT_DIR"
-       BURN_METHOD="DVD directly"
+        echo "Using disk label \"$VOLID\""
     fi
-
+    
+    # Burn it already!
+    BURN_CMD="growisofs -use-the-force-luke=dao -dvd-compat $BURN_SPEED -Z $DVDRW_DEVICE -dvd-video -V \"$VOLID\" $OUT_DIR"
     echo $SEPARATOR
-    echo "Burning $BURN_METHOD with growisofs $GROWISOFS_VER using the following command:"
+    echo "Burning with growisofs $GROWISOFS_VER using the following command:"
     echo "$BURN_CMD"
     echo $SEPARATOR
-
     if eval "$BURN_CMD" 2>&1; then
         echo $SEPARATOR
         echo "Done. You should now have a working DVD. Please visit"
@@ -385,7 +335,6 @@ if $DO_BURN; then
     else
         runtime_error "Could not burn the disc to $DVDRW_DEVICE"
     fi
-
 fi
     
 echo $SEPARATOR
