* more work on transcode nav_seek changes   animated submenus working now

diff --git a/tovid/src/todisc b/tovid/src/todisc
--- a/tovid/src/todisc
+++ b/tovid/src/todisc
@@ -717,6 +717,7 @@ if $SUB_MENU; then
         [ -z "$MIN_CHAPTERS" ]  || ((chapt_val < MIN_VAL)) && MIN_CHAPTERS=$chapt_val && min_chapt_key=$i
     done
 fi
+echo "MAX_CHAPTERS are $MAX_CHAPTERS"
 # do not let user use -chapters 0 (-chapters 5 0 6)
 if $SUB_MENU; then
     for ((i=0; i<${#CHAPTERS[@]}; i++)); do
@@ -750,7 +751,7 @@ if $ANI_SUB_MENU; then
         mkdir -v "$REAL_WORK_DIR/animenu/$i"
     done
 fi
-if $SUB_MENUS; then
+if $SUB_MENU; then
     mkdir -v "$REAL_WORK_DIR/submenu"
 fi
 # if Fading menu, and no BG IMAGE OR VIDEO, fade thumbs right in after title
@@ -1411,10 +1412,21 @@ fi
 
 # Store info about input files in an array
 for ((i=0; i<${#IN_FILES[@]}; i++)); do
-    echo "Getting stats on "${IN_FILES[i]}""
-    if [ $SEEK_VAL -gt 450 ]; then
+    # use a nav_seek file and transcode if long seek
+    if [[ $SEEK_VAL -gt 450 || $SUB_MENU ]]; then
+        NAVSEEK="--nav_seek "$WORK_DIR/nav${i}_log""
         STATS_FRAMES="-frames 1"
+        if [ ! -e "$WORK_DIR/nav${i}_log" ]; then
+            yecho "Creating a nav_seek log with tcdemux to speed up seeking"
+            NAVSEEK_CMD=(nice tcdemux -f $FRAME_RATE -W -i "${IN_FILES[i]}")
+            yecho "Running "${NAVSEEK_CMD[@]}" > "$WORK_DIR/nav${i}_log""
+            length=( ${length[@]} $("${NAVSEEK_CMD[@]}" 2>&1 |
+            tee "$WORK_DIR/nav${i}_log"  |awk '/detected/ {print $2}') )
+            echo "length[@] is ${length[@]}"
+#            "${NAVSEEK_CMD[@]}"  > "$WORK_DIR/nav${i}_log"
+        fi
     fi
+    echo "Getting stats on "${IN_FILES[i]}""
     mencoder_stats=( "${mencoder_stats[@]}" \
     "$(mencoder -quiet "${IN_FILES[i]}" -oac pcm -ovc copy $STATS_FRAMES -o /dev/null 2>&1)" )
 done
@@ -1432,8 +1444,8 @@ for ((i=0; i<${#IN_FILES[@]}; i++)); do
     if [ -z "$A_BR" ]; then
         A_BR="No audio found"
     fi
-    if [ $SEEK_VAL -gt 450 ]; then
-        V_LENGTH=$(awk_math ${length[i]} by 60 float)
+    if [ -e "$WORK_DIR/nav${i}_log" ]; then
+        V_LENGTH=$(awk_math ${length[i]} by $FRAME_RATE float)
     else
         V_LENGTH="$(awk '/Video stream:/{print $10}'<<<"${mencoder_stats[i]}")"
     fi
@@ -1456,7 +1468,7 @@ echo
 echo $SEPARATOR
 
 for ((i=0; i<${#mencoder_stats[@]}; i++)); do
-    if [ $SEEK_VAL -gt 450 ]; then
+    if [ -e "$WORK_DIR/nav${i}_log" ]; then
         VID_LEN=( ${VID_LEN[@]}  $(awk_math ${length[i]} by 60 float) )
     else
         VID_LEN=( ${VID_LEN[@]}  "$(awk '/Video stream:/{print $10}' \
@@ -1520,7 +1532,7 @@ echo "Creating images from each video for the main menu"
 for ((i=0; i<=NUM_FILES; i++)) ; do
     echo "Working on "${IN_FILES[i]}""
     # use a nav_seek file and transcode if long seek
-    if [ $SEEK_VAL -gt 450 ]; then
+    if [[ $SEEK_VAL -gt 450 || $SUB_MENU ]]; then
         NAVSEEK="--nav_seek "$WORK_DIR/nav${i}_log""
         if [ ! -e "$WORK_DIR/nav${i}_log" ]; then
             NAVSEEK_CMD=(nice tcdemux -f $FRAME_RATE -W -i "${IN_FILES[i]}")
@@ -1761,7 +1773,7 @@ if $SUB_MENU; then
         if $ANI_SUB_MENU; then
             JPEG2YUV_OPTS=(-n $ANI_SUBMENU_FRAMES)
             PICS_IN=($WORK_DIR/animenu/%0d.$SM_IMG_FMT)
-            PICS_OUT=($WORK_DIR/animenu/chapt)
+            PICS_OUT=($WORK_DIR/animenu/)
             CUT_TIME=340
             JPEG_DIR="$WORK_DIR/animenu"
             SLEEP=1
@@ -1793,22 +1805,54 @@ if $SUB_MENU; then
             "${NAVSEEK_CMD[@]}" > "$WORK_DIR/nav${i}_log"
         fi
         NAVSEEK="--nav_seek "$WORK_DIR/nav${i}_log""
+        yecho
+        yecho "Creating $TOTAL_JPEGS chapter images for "${IN_FILES[i]}""
+        yecho
         for t in "${cmd[@]}"; do
-            echo
             echo "Running nice transcode --print_status 340 -q 1 -i "${IN_FILES[i]}" \
             $NAVSEEK -o $WORK_DIR/submenu/ \
             -f $FRAME_RATE -Z ${GEO_ARRAY[C]},fast -c $t -y $SM_IMG_FMT,null
             " | sed 's/    */ /g'|sed -e "s/^ *//"|tee -a "$LOG_FILE"
             nice transcode --print_status 340 -q 1 -i "${IN_FILES[i]}" \
-            $NAVSEEK -o $WORK_DIR/submenu/ \
+            $NAVSEEK -o "${PICS_OUT[@]}" \
             -f $FRAME_RATE -Z ${GEO_ARRAY[C]},fast -c $t \
             -y $SM_IMG_FMT,null >> "$LOG_FILE" 2>&1
-            echo
-            mv -v $WORK_DIR/submenu/000000.$SM_IMG_FMT \
-            $WORK_DIR/submenu/$(printf "%08d%s\n" ${t%-*} .$SM_IMG_FMT)
+            if ! $ANI_SUB_MENU ; then
+                echo
+                mv $WORK_DIR/submenu/000000.$SM_IMG_FMT \
+                $WORK_DIR/submenu/$(printf "%08d%s\n" ${t%-*} .$SM_IMG_FMT)
+            elif $ANI_SUB_MENU; then
+                echo "moving images to new filenames so they won't be overwritten"
+                echo
+                u=${t/*-} 
+                for ((n=0; n<340; n++)); do
+                    mv $WORK_DIR/animenu/$(printf "%06d%s\n" $n .jpg) \
+                    $WORK_DIR/animenu/$(printf "%08d%s\n" $((n+u)) .jpg)
+                done
+            fi
         done
-        yecho
-        yecho "Creating $TOTAL_JPEGS chapter images for "${IN_FILES[i]}""
+            if $ANI_SUB_MENU ; then
+                # FIXME make sure $CHAPTERS number of images got created
+                # move 340 images to each subdir:  $WORK_DIR/animenu/{0,1,2,3,etc}
+                echo "moving images into subdirectories"
+                for ((a=0; a<${CHAPTERS[i]}; a++)); do
+                    pics=( $(find $WORK_DIR/animenu/ -maxdepth 1 -name 00\*.$SM_IMG_FMT |
+                    sort|head -n 340) )
+                    echo "${pics[@]}" >> "$WORK_DIR/pics.log"
+                    for f in ${pics[@]}; do
+                        mv $f $WORK_DIR/animenu/$a
+                    done
+                done
+                for ((a=0; a<${CHAPTERS[i]}; a++)); do
+                    find $WORK_DIR/animenu/$a/ -name 00\*.$SM_IMG_FMT |
+                    sort| head -n 20|xargs rm -f
+                    find $WORK_DIR/animenu/$a/ -name 00\*.$SM_IMG_FMT |
+                    sort|tail -n 20|xargs rm -f
+                done
+                # clean up left over pics in animenu/ dir
+                echo "Cleaning up leftover pics in $REAL_WORK_DIR/animenu"
+                rm -f $WORK_DIR/animenu/*.$SM_IMG_FMT
+            fi
 
 #        echo "Running  "${TCODE_CMD[@]}"" >> "$LOG_FILE"
 #        echo "Running  "${TCODE_CMD[@]}""
@@ -1839,24 +1883,6 @@ if $SUB_MENU; then
         unset TCODE_CMD cmd
 UNUSED
         if $ANI_SUB_MENU; then
-            # FIXME make sure $CHAPTERS number of images got created
-            # move 340 images to each subdir:  $WORK_DIR/animenu/{0,1,2,3,etc}
-            for ((a=0; a<${CHAPTERS[i]}; a++)); do
-                pics=( $(find $WORK_DIR/animenu/ -maxdepth 1 -name chapt\*.$SM_IMG_FMT |
-                sort|head -n 340) )
-                for f in ${pics[@]}; do
-                    mv  $f $WORK_DIR/animenu/$a
-                done
-            done
-            for ((a=0; a<${CHAPTERS[i]}; a++)); do
-                find $WORK_DIR/animenu/$a/ -name chapt\*.$SM_IMG_FMT |
-                sort| head -n 20|xargs rm
-                find $WORK_DIR/animenu/$a/ -name chapt\*.$SM_IMG_FMT |
-                sort|tail -n 20|xargs rm
-            done
-            # clean up left over pics in animenu/ dir
-            echo "Cleaning up leftover pics in $REAL_WORK_DIR/animenu"
-            rm -f $WORK_DIR/animenu/*.$SM_IMG_FMT
             echo
             echo "Making 300 montage images for "${IN_FILES[i]}""
 
@@ -2056,7 +2082,7 @@ UNUSED
         rm -fv $WORK_DIR/menu$s.wav
     done
     rm -fv $WORK_DIR/submenu.{wav,$AUDIO_EXT}
-    rm -fr $WORK_DIR/animenu/*
+#    rm -fr $WORK_DIR/animenu/*
 fi
 
 ##############################################################################
