* fix for sort order of preview montages * changes to spinner monitoring * sort %06d jpeg arrays (transcode) to be more sure of order

diff --git a/tovid/src/todisc b/tovid/src/todisc
--- a/tovid/src/todisc
+++ b/tovid/src/todisc
@@ -295,7 +295,8 @@ function spin()
     SPINNER="${SPIN_CHARS:SP++%${#SPIN_CHARS}:1}"
     # Print spaces to overwrite previous line
     echo -ne "\r                                                            "
-    echo -ne "\r$@ $SPINNER   "
+#    echo -ne "\r$@ $SPINNER   "
+    echo -ne "\r$@ "
 }
 
 ##############################################################################
@@ -920,7 +921,7 @@ convert -size 620x100 xc:none -font "$MENU_FONT" \
 convert -trim +repage - -blur 0x0.4 $WORK_DIR/title_txt.png
 
 if $MIST; then
-    echo "making a white or colored png for the misted title background"
+    echo "Making a white or colored png for the misted title background"
     echo
     # make a white or coloured png for misted background effect, only for user's bg
     Y=$(identify $WORK_DIR/title_txt.png |awk '{print $3}'|cut -dx -f1)
@@ -955,7 +956,6 @@ if [ -n "$BG_VIDEO" ]; then
         exit 1
     fi
 fi
-
 for ((i=0; i<=NUM_FILES; i++)) ; do
     FFMPEG_CMD=(ffmpeg -i "${IN_FILES[i]}" $SEEK -vframes 1 \
     -s $THUMB_SIZE $WORK_DIR/${i}-preview%d.$IMG_FMT)
@@ -975,8 +975,11 @@ if $MIST; then
     $WORK_DIR/white.png $WORK_DIR/pics/template.png \
     $WORK_DIR/pics/template.png
 fi
+# sort -n would probably work ok, but lets be sure of order with a loop
+for ((i=0; i<=NUM_FILES; i++)); do
 PICS=( "${PICS[@]}" \
-$(find $WORK_DIR/ -maxdepth 1 -name \*preview\*.$IMG_FMT | sort) )
+    $(find $WORK_DIR/ -maxdepth 1 -name ${i}-preview\*.$IMG_FMT) )
+done
 for ((i=0; i<${#PICS[@]}; i++)); do
     if $FEATHER; then
         composite -compose CopyOpacity $THUMB_MASK +matte \
@@ -1082,16 +1085,21 @@ for ((i=0; i<${#NEW_LENGTH[@]}; i++)); do
         [ -z "$MIN_VAL" ]  || ((val < MIN_VAL)) && MIN_VAL=$val && min_key=$i
     fi
 done
-# if shortest is less than 340 frames * $CHAPTERS then no animated submenu
-for ((i=0; i<NUM_FILES; i++)); do
-    if $ANI_SUB_MENU && [ $MIN_VAL -lt $(((340 * ${CHAPTERS[i]}) / 30)) ]; then
-        echo -n "Sorry, the shortest length video must be greater than "
-        echo "$(((340 * ${CHAPTERS[i]})) / 30)) seconds"
-        echo "to use animated submenus."
-        echo "${IN_FILES[min_key]} is only $MIN_VAL seconds long"
-        exit 1
-    fi 
-done
+# if animated submenu check if videos are long enough for the # of chapters
+if $ANI_SUB_MENU; then
+    for ((i=0; i<=NUM_FILES; i++)); do
+        S=$(awk_math $SEEK_VAL times $FRAME_RATE)
+        F=$(awk_math  "${CHAPTERS[i]}" times 340 )
+        V=$(awk_math "${VID_LEN[i]}" times $FRAME_RATE)
+        if [ $((V - S)) -le $F ] ; then
+            echo "Sorry, you can not use ${CHAPTERS[i]} chapters for ${IN_FILES[i]}"
+            echo "The maximum number for this video (using a -seek of $SEEK_VAL):"
+            echo "$(awk_math $((V - S)) by 340) chapters" 
+            exit 1
+        fi 
+        unset V F
+    done
+fi
 # allow animated menus of length of longest video
 MAX_ANI_LENGTH=$(awk_math $FRAME_RATE times $ANI_MENU_LENGTH)
 MAX_VAL_FRAMES="$(($MAX_VAL * 30))"
@@ -1182,12 +1190,13 @@ done
 for ((s=0; s<=NUM_FILES; s++)); do
     # make appropriate chapter lengths for each video
     # get chapter lengths by dividing by $CHAPTERS, then getting running totals
-    CHAPT_INTERVALS=( ${CHAPT_INTERVALS[@]} "$(awk_math ${NEW_LENGTH[s]} by ${CHAPTERS[s]} float)" )
+    CHAPT_INTERVALS=( ${CHAPT_INTERVALS[@]} "$(awk_math ${VID_LEN[s]} by ${CHAPTERS[s]} float)" )
     # and format in HH:MM:SS
     L=( ${L[@]} $(for ((i=1; i<=${CHAPTERS[s]}; i++)) ; do echo "${CHAPT_INTERVALS[s]}";done) )
     chapt_intervals=$(running_total <<< ${L[@]})
     chapters="$(for c in $chapt_intervals; do echo $(format_seconds $c); done)"
     chapters="00:00:00.000 $chapters"
+    if [ ${CHAPTERS[s]} = 1 ]; then chapters="00:00:00.000"; fi
     CHAPTS=$(for i in $chapters; do echo -n $i,;done|sed 's/,$//')
     CHAPT_ARRAY[s]="$CHAPTS"
     unset L cmd
@@ -1355,12 +1364,19 @@ if $SUB_MENU; then
             PICS_IN=($WORK_DIR/animenu/%0d.$SM_IMG_FMT)
             PICS_OUT=($WORK_DIR/animenu/chapt)
             CUT_TIME=340
+            JPEG_DIR="$WORK_DIR/animenu"
+            SLEEP=1
+            TOTAL_JPEGS=$((340 * ${CHAPTERS[i]}))
 
         else  # not animated submenu
             JPEG2YUV_OPTS=(-n 1 -l 60)
             PICS_IN=($WORK_DIR/${i}-submenu.$SM_IMG_FMT)
             PICS_OUT=($WORK_DIR/${i}-chapt)
             CUT_TIME=1
+            JPEG_DIR=$WORK_DIR
+            SLEEP=.1
+            TOTAL_JPEGS=${CHAPTERS[i]}
+            PREFIX=${i}-
         fi    
         counts=$(awk_math ${CHAPT_INTERVALS[i]} times $FRAME_RATE)
         CUT=( 30 $(running_total <<<  $(for ((a=0; a<${CHAPTERS[i]} ; a++)); \
@@ -1371,52 +1387,67 @@ if $SUB_MENU; then
         key=$((${#cmd[@]} - 1))
         unset cmd[key]
         CMD=$(echo ${cmd[@]} |  sed 's/ /,/g;s/,$//')
-        TCODE_CMD=(nice transcode -q 0 -i "${IN_FILES[i]}" -o "${PICS_OUT[@]}" \
+        TCODE_CMD=(nice transcode --print_status $((340 * ${CHAPTERS[i]}))  -q 1 -i "${IN_FILES[i]}" -o "${PICS_OUT[@]}" \
         -f $FRAME_RATE -Z ${GEO_ARRAY[C]},fast -c "$CMD" -y $SM_IMG_FMT,null)
         yecho
-        yecho "Creating chapter images for "${IN_FILES[i]}""
+        yecho "Creating $TOTAL_JPEGS chapter images for "${IN_FILES[i]}""
 
-        echo "Running  "${TCODE_CMD[@]}"" >> $LOG_FILE
-        yecho "Running  "${TCODE_CMD[@]}""
-        "${TCODE_CMD[@]}" >> $LOG_FILE.tmp  2>&1 & 
+#        echo "Running  "${TCODE_CMD[@]}"" >> $LOG_FILE
+        echo "Running  "${TCODE_CMD[@]}""
+        # sleep after transcode, so the spinner picks all the jpegs up
+        function run_transcode()
+        {
+            "${TCODE_CMD[@]}" >> $LOG_FILE.tmp  2>&1
+            sleep 3
+        }
+        run_transcode &
         TCODE_PID="$!"
         sleep .5 # short sleep to allow 1st jpg to appear
         if [ -n "$TCODE_PID" ]; then
             while ps -p $TCODE_PID >/dev/null; do
-                sleep .5 # spinner interval
-                spin "Created $(ls $WORK_DIR/${i}-chapt*.jpg 2>/dev/null | tail -n 1) "
+                sleep $SLEEP # spinner interval
+            spin "Seeking in video and creating images: $(find $JPEG_DIR \
+            -maxdepth 1 -name $PREFIX\*chapt\*.jpg|sort|tail -n 1)"
             done
+            echo
+            echo "Created $(find $JPEG_DIR -maxdepth 1 -name $PREFIX\*chapt\*.jpg|wc -l) JPEGS"
             cleanlog 1
         else
             cleanlog 1
             runtime_error "Problem creating images from the video."
             exit 1
         fi
-        unset TCODE_CMD
+        unset TCODE_CMD cmd
 
         if $ANI_SUB_MENU; then
             # FIXME make sure $CHAPTERS number of images got created
             # move 340 images to each subdir:  $WORK_DIR/animenu/{0,1,2,3,etc}
             for ((a=0; a<${CHAPTERS[i]}; a++)); do
-                pics=( $(find $WORK_DIR/animenu/ -maxdepth 1 -name chapt\*.$SM_IMG_FMT|
-                head -n 340) )
+                pics=( $(find $WORK_DIR/animenu/ -maxdepth 1 -name chapt\*.$SM_IMG_FMT |
+                sort|head -n 340) )
                 for f in ${pics[@]}; do
-                    mv $f $WORK_DIR/animenu/$a
+                    mv  $f $WORK_DIR/animenu/$a
                 done
             done
             for ((a=0; a<${CHAPTERS[i]}; a++)); do
-                find $WORK_DIR/animenu/$a/ -name chapt\*.$SM_IMG_FMT|head -n 20|xargs rm
-                find $WORK_DIR/animenu/$a/ -name chapt\*.$SM_IMG_FMT|tail -n 20|xargs rm
+                find $WORK_DIR/animenu/$a/ -name chapt\*.$SM_IMG_FMT |
+                sort| head -n 20|xargs rm
+                find $WORK_DIR/animenu/$a/ -name chapt\*.$SM_IMG_FMT |
+                sort|tail -n 20|xargs rm
             done
+            # clean up left over pics in animenu/ dir
+            echo "Cleaning up leftover pics in $WORK_DIR/animenu"
+            rm -f $WORK_DIR/animenu/*.$SM_IMG_FMT
             echo
-            echo "Making montage images for "${IN_FILES[i]}""
+            echo "Making 300 montage images for "${IN_FILES[i]}""
 
             for ((a=1; a<300; a++)); do
-                echo -ne "\r                                                            "
-                echo -ne "\rProcessing "$WORK_DIR/animenu/$a.$SM_IMG_FMT"  "
+#                echo -ne "\r                                                            "
+#                echo -ne "\rProcessing "$WORK_DIR/animenu/$a.$SM_IMG_FMT"  "
+                spin "\rProcessing "$WORK_DIR/animenu/$a.$SM_IMG_FMT"  "
                 for ((b=0; b<${CHAPTERS[i]}; b++)); do
                     IMGS=( "${IMGS[@]}" $(find $WORK_DIR/animenu/$b \
-                    -name \*.$SM_IMG_FMT|head -n $a|sed  -n -e "$a p") )
+                    -name \*.$SM_IMG_FMT| sort|head -n $a | sed -n -e "$a p") )
                 done
                 IM_CMD=(montage ${IMGS[@]} -tile ${TILE_ARRAY[C]} \
                 -geometry ${GEO_ARRAY[C]}+5+5 -bordercolor '#161514' \
@@ -1437,11 +1468,11 @@ if $SUB_MENU; then
             yecho
             yecho "Making montage images for "${IN_FILES[i]}""
             # just use $CHAPTERS number of images
-            imgs=( $(find $WORK_DIR -name ${i}-chapt000\*.$SM_IMG_FMT|head -n ${CHAPTERS[i]}) )
+            imgs=( $(find $WORK_DIR -name ${i}-chapt000\*.$SM_IMG_FMT |
+            sort| head -n ${CHAPTERS[i]}) )
             # create frames for the chapter thumbs
             for PIC in "${imgs[@]}"; do
-            echo -ne "\r                                                            "
-            echo -ne "\rProcessing "$PIC"  "
+            spin "\rProcessing "$PIC"  "
                 convert -background '#141614' -frame 5x5 \
                 -bordercolor none -mattecolor "#444744" "$PIC" miff:- |
                 convert -resize "${GEO_ARRAY[C]}"! - "$PIC"
@@ -1469,7 +1500,6 @@ if $SUB_MENU; then
             cleanlog 3
             runtime_error
         fi
-        rm -f $WORK_DIR/animenu/*.$IMG_FMT
     done    
     unset IMG_STREAM_CMD1 ENC_CMD1 JPEG2YUV_OPTS
     for ((s=0; s<=NUM_FILES; s++)); do
@@ -1585,6 +1615,7 @@ if $SUB_MENU; then
         rm -fv $WORK_DIR/menu$s.wav
     done
     rm -fv $WORK_DIR/submenu.{wav,$AUDIO_EXT}
+    rm -fr $WORK_DIR/animenu/*
 fi
 
 ##############################################################################
@@ -1627,8 +1658,9 @@ for ((i=0; i<=NUM_FILES; i++)); do
     echo
     yecho "Working on ${#PICS[@]} images from ${IN_FILES[i]}"
     for pic in "${PICS[@]}"; do
-        echo -ne "\r                                                            "
-        echo -ne "\rProcessing "$pic"  "
+#        echo -ne "\r                                                            "
+#        echo -ne "\rProcessing "$pic"  "
+        spin "\rProcessing "$pic"  "
         IM_CMD0=(composite -compose CopyOpacity $THUMB_MASK +matte \
         "$pic")
         IM_CMD1=(convert -trim +repage -)
@@ -1644,7 +1676,6 @@ for ((i=0; i<=NUM_FILES; i++)); do
         -bordercolor none -mattecolor "#444744" -)
         IM_CMD5=(convert -resize $THUMB_SIZE! - $pic)
         if $FEATHER; then
-#            "${IM_CMD0[@]}" miff:- | "${IM_CMD2[@]}" miff:- | "${IM_CMD1[@]}" miff:- |
             "${IM_CMD0[@]}" miff:- | "${IM_CMD2[@]}" miff:- |
             "${IM_CMD2b[@]}" miff:- |"${IM_CMD2c[@]}" miff:- |
             "${IM_CMD1[@]}" miff:- | "${IM_CMD5[@]}"
@@ -1698,8 +1729,8 @@ if $MENU_FADE && ! $STATIC; then
 
         # TODO: More descriptive message about what this loop is doing
 #        spin "Working..."
-        echo -ne "\r                                                            "
-        echo -ne "\rProcessing "$WORK_DIR/animenu/$(($frame + 1)).jpg"  "
+#        echo -ne "\r                                                            "
+        spin -ne "\rProcessing "$WORK_DIR/animenu/$(($frame + 1)).jpg"  "
          
 
         ANI_PICS=( $(find $WORK_DIR/pics/*[0-9]* -maxdepth 1 -name $((frame + 1)).$IMG_FMT) )
@@ -1738,8 +1769,9 @@ else # Do not do menu fade
 
             # TODO: More descriptive message about what this loop is doing
 #            spin "Working..."
-            echo -ne "\r                                                            "
-            echo -ne "\rProcessing "$WORK_DIR/animenu/$count.jpg"  "
+#            echo -ne "\r                                                            "
+#            echo -ne "\rProcessing "$WORK_DIR/animenu/$count.jpg"  "
+            spin "\rProcessing "$WORK_DIR/animenu/$count.jpg"  "
 
             ANI_PICS=$(find $WORK_DIR/pics/*[0-9]* -maxdepth 1 -name $count.$IMG_FMT)
             IM_CMD1=(montage ${ANI_PICS[@]} -tile ${TILE_ARRAY[NUM_FILES]} \
@@ -1762,7 +1794,11 @@ else # Do not do menu fade
                 "${IM_CMD1[@]}" | "${IM_CMD2[@]}" | "${IM_CMD3[@]}" | "${IM_CMD4[@]}"
                 fi
             else
-                "${IM_CMD1[@]}" | "${IM_CMD2[@]}" | "${IM_CMD4[@]}"
+                if test -n "$BG_VIDEO"; then
+                    "${IM_CMD1[@]}" | "${IM_CMD2b[@]}" | "${IM_CMD4[@]}"
+                else
+                    "${IM_CMD1[@]}" | "${IM_CMD2[@]}" | "${IM_CMD4[@]}"
+                fi
             fi
             rm -f ${ANI_PICS[@]}
         done
@@ -1771,8 +1807,9 @@ else # Do not do menu fade
 
             # TODO: More descriptive message about what this loop is doing
 #            spin "Working..."
-            echo -ne "\r                                                            "
-            echo -ne "\rProcessing "$WORK_DIR/animenu/$count.jpg"  "
+#            echo -ne "\r                                                            "
+#            echo -ne "\rProcessing "$WORK_DIR/animenu/$count.jpg"  "
+            spin -ne "\rProcessing "$WORK_DIR/animenu/$count.jpg"  "
 
             ANI_PICS=$(find $WORK_DIR/pics/*[0-9]* -maxdepth 1 -name $count.$IMG_FMT)
 
