Cleanup, fixed outdir and working dir issues

diff --git a/tovid/src/tovid b/tovid/src/tovid
--- a/tovid/src/tovid
+++ b/tovid/src/tovid
@@ -298,15 +298,15 @@ check_disk_space()
     AVAIL_SPACE=$(df -mP . | awk 'NR != 1 {print $4;}')
     # Rough estimates of KB/sec for different formats
     K_PER_SEC=200
-    test x"$TGT_RES" = x"VCD" && K_PER_SEC=172
-    test x"$TGT_RES" = x"DVD-VCD" && K_PER_SEC=200
-    test x"$TGT_RES" = x"Half-DVD" && K_PER_SEC=300
-    test x"$TGT_RES" = x"DVD" && K_PER_SEC=350
-    test x"$TGT_RES" = x"SVCD" && K_PER_SEC=300
+    test "$TGT_RES" = "VCD" && K_PER_SEC=172
+    test "$TGT_RES" = "DVD-VCD" && K_PER_SEC=200
+    test "$TGT_RES" = "Half-DVD" && K_PER_SEC=300
+    test "$TGT_RES" = "DVD" && K_PER_SEC=350
+    test "$TGT_RES" = "SVCD" && K_PER_SEC=300
 
     # If video length is unknown, guess needed space
     # based on original file size
-    if test x"$V_DURATION" = x"0"; then
+    if test "$V_DURATION" = "0"; then
         CUR_SIZE=$(du -c -k \"$IN_FILE\" | awk 'END{print $1}')
         NEED_SPACE=$(expr $CUR_SIZE \* 2)
         yecho  "The encoding process will require about"
@@ -456,9 +456,9 @@ get_args()
                 ;;
             "-priority" )
                 shift
-                if test x"$1" = x"low"; then
+                if test "$1" = "low"; then
                     PRIORITY="nice -n 19"
-                elif test x"$1" = x"medium"; then
+                elif test "$1" = "medium"; then
                     PRIORITY="nice -n 10"
                 fi
                 ;;
@@ -528,8 +528,6 @@ get_args()
             "-out" )
                 shift
                 OUT_PREFIX="$1"
-                # Use full pathname with extension (mpg)
-                OUT_FILENAME=$(abspath "$1").mpg
                 ;;
 
             # Null option; ignored.
@@ -554,6 +552,9 @@ get_args()
             "*" )
                 usage_error "Unrecognized command-line option '$1'"
                 ;;
+            * )
+                echo "Ignoring option '$1'"
+                ;;
             esac
 
         # Get next argument
@@ -569,7 +570,7 @@ get_args()
         if test -r "$CONFIG_FILE"; then
             # Make sure file is a tovid config file
             CONFIG_TYPE=$(head -n 1 "$CONFIG_FILE")
-            if test x"$CONFIG_TYPE" != x"tovid"; then
+            if test "$CONFIG_TYPE" != "tovid"; then
                 yecho "$CONFIG_FILE is not a valid tovid configuration file."
                 yecho "Skipping $CONFIG_FILE"
             else
@@ -578,7 +579,7 @@ get_args()
                 yecho "Using config file $CONFIG_FILE, containing the following options:"
                 if test -n "$CONFIG_ARGS"; then
                     yecho "$CONFIG_ARGS"
-                    get_args "$CONFIG_ARGS"
+                    get_args $CONFIG_ARGS
                 else
                     yecho "(none)"
                 fi
@@ -600,13 +601,13 @@ cleanup()
     rm -fv stream.yuv
     if $KEEPFILES; then
         yecho "Keeping temporary files:"
-        yecho "  $OUT_PREFIX.$VID_SUF"
-        yecho "  $OUT_PREFIX.$AUD_SUF"
+        yecho "  $VIDEO_STREAM"
+        yecho "  $AUDIO_STREAM"
         yecho "  $AUDIO_WAV"
     else
         yecho "Removing temporary files..."
-        rm -fv "$OUT_PREFIX.$VID_SUF"
-        rm -fv "$OUT_PREFIX.$AUD_SUF"
+        rm -fv "$VIDEO_STREAM"
+        rm -fv "$AUDIO_STREAM"
         rm -fv "$AUDIO_WAV"
     fi
 
@@ -651,15 +652,25 @@ if ! $QUIET; then
 fi
 get_args "$@"
 
-# ******************************************************************************
-# Do all work in the working directory
-# ******************************************************************************
-$QUIET || echo "Changing to working directory: $WORKING_DIR"
-cd "$WORKING_DIR"
 
 # ******************************************************************************
-# Make all necessary dependencies are available, to prevent errors later
+#
+# Sanity checks
+#
 # ******************************************************************************
+
+# Check for presence of mplayer and mpeg2enc
+assert_dep mplayer 'no mplayer'
+assert_dep mmplayer 'no mmplayer, foo'
+assert_dep mmpeg2enc 'no mmpeg2enc, foo'
+
+# Can't do -subtitles with -ffmpeg; if both were used, print error and exit
+# TODO: Support subtitles in ffmpeg!
+if $USE_FFMPEG && $DO_SUBS; then
+    usage_error "Sorry, -subtitles is not currently supported with -ffmpeg."
+fi
+
+
 if type mplayer >/dev/null; then :; else
     echo "$ME It looks like you don't have mplayer installed. I need mplayer"
     echo "for playing and encoding video. You can get mplayer from:"
@@ -673,22 +684,9 @@ if type mpeg2enc >/dev/null; then :; else
     exit 1
 fi
 
-# ******************************************************************************
-# Sanity checks. Make sure input file exists, and see if we're going
-# to overwrite any existing output files.
-# ******************************************************************************
-
-# Make sure infile and outfile were provided somewhere
+# Make sure '-in FILE' was provided on the command-line
 if test -z "$IN_FILE"; then
     usage_error "Please provide an input filename with the -in option."
-fi
-if test -z "$OUT_PREFIX"; then
-    usage_error "Please provide an output name with the -out option."
-fi
-
-# Can't do -subtitles with -ffmpeg; if both were used, print error and exit
-if $USE_FFMPEG && $DO_SUBS; then
-    usage_error "Sorry, -subtitles is not currently supported with -ffmpeg."
 fi
 
 # Determine whether input is a normal file or a URI of some sort
@@ -699,8 +697,9 @@ else
     IN_FILE_TYPE="file"
 fi
 
+
 # Make sure infile exists
-if test x"$IN_FILE_TYPE" = x"file"; then
+if test "$IN_FILE_TYPE" = "file"; then
     if test -e "$IN_FILE"; then
         :
     else
@@ -708,33 +707,60 @@ if test x"$IN_FILE_TYPE" = x"file"; then
     fi
 fi
 
+if test -z "$OUT_PREFIX"; then
+    usage_error "Please provide an output name with the -out option."
+fi
+
 # check that outfile is not a directory
 if test -d "$OUT_PREFIX"; then
     exit_with_error "Error: The specified output file is a directory.  A filename must be specified."
+# If output prefix is a base name only, put output in OUTPUT_DIR
+elif test "$OUT_PREFIX" = $(basename "$OUT_PREFIX"); then
+    OUT_PREFIX="$OUTPUT_DIR/$OUT_PREFIX"
+# Otherwise, use the full qualified pathname
+else
+    OUT_PREFIX=$(abspath "$OUT_PREFIX")
 fi
 
 # If output file(s) exist, prompt for overwrite
-if test -e "$OUT_PREFIX.$VID_SUF" || test -e "$OUT_FILENAME" || test -e "$OUT_PREFIX.$AUD_SUF"; then
+if test -e "$VIDEO_STREAM" || test -e "$OUT_FILENAME" || test -e "$AUDIO_STREAM"; then
     yecho "It looks like some files already exist with prefix: $OUT_PREFIX"
     if $OVERWRITE; then
         yecho "Removing existing files..."
-        rm -fv "$OUT_PREFIX.$VID_SUF" "$OUT_FILENAME" "$OUT_PREFIX.$AUD_SUF"
+        rm -fv "$VIDEO_STREAM" "$OUT_FILENAME" "$AUDIO_STREAM"
     else
         exit_with_error "If you would like to overwrite the existing files, please re-run the script with the 'overwrite' option."
     fi
 fi
 
-# Create a unique temporary directory
-TMP_DIR=$(mktemp -d "${WORKING_DIR}/tovid-temp.XXXXXX")
+
+# ******************************************************************************
+#
+# Execution setup; change to work directory, create tempdir and log file(s)
+#
+# ******************************************************************************
+$QUIET || echo "Changing to working directory: $WORKING_DIR"
+cd "$WORKING_DIR"
+
+# Create a unique temporary directory, named after the given -out name
+OUTNAME=$(basename "$OUT_PREFIX")
+TMP_DIR=$(mktemp -d "$WORKING_DIR/$OUTNAME.XXXXXX")
 # Files to use for temporarily storing video info and encoding progress
-SCRATCH_FILE="${TMP_DIR}/tovid.scratch"
-LOG_FILE="${TMP_DIR}/tovid.log"
+SCRATCH_FILE="$TMP_DIR/tovid.scratch"
+LOG_FILE="$TMP_DIR/tovid.log"
 
 # Remove temp and log files if they exist
 rm -f "$SCRATCH_FILE" "$LOG_FILE"
 # Print current command-line to log
 echo "$ME $0 $@" >> "$LOG_FILE"
 echo "$ME Version $TOVID_VERSION" >> "$LOG_FILE"
+
+# Full pathnames for A/V streams and output file
+AUDIO_STREAM="$TMP_DIR/audio.$AUD_SUF"
+VIDEO_STREAM="$TMP_DIR/video.$VID_SUF"
+OUT_FILENAME="$OUT_PREFIX.mpg"
+
+
 
 # ******************************************************************************
 #
@@ -760,7 +786,7 @@ case "$TVSYS" in
     "NTSCFILM" )
         VID_NORM="--video-norm n"
         # VCD can't use 3:2 pulldown; all others can
-        if test x"$TGT_RES" = x"VCD"; then
+        if test "$TGT_RES" = "VCD"; then
             VID_FPS="--frame-rate 2"
         else
             VID_FPS="--frame-rate 4 --3-2-pulldown"
@@ -827,7 +853,7 @@ case "$TGT_RES" in
     # VCD
     "VCD" )
         TGT_WIDTH="352"
-        if test x"$TVSYS" = x"PAL"; then
+        if test "$TVSYS" = "PAL"; then
             TGT_HEIGHT="288"
         else
             TGT_HEIGHT="240"
@@ -844,7 +870,7 @@ case "$TGT_RES" in
     # KVCD: VCD resolution, but using MPEG-2 and with KVCD quantization
     "KVCD" )
         TGT_WIDTH="352"
-        if test x"$TVSYS" = x"PAL"; then
+        if test "$TVSYS" = "PAL"; then
             TGT_HEIGHT="288"
         else
             TGT_HEIGHT="240"
@@ -862,7 +888,7 @@ case "$TGT_RES" in
     # VCD-on-DVD
     "DVD-VCD" )
         TGT_WIDTH="352"
-        if test x"$TVSYS" = x"PAL"; then
+        if test "$TVSYS" = "PAL"; then
             TGT_HEIGHT="288"
         else
             TGT_HEIGHT="240"
@@ -880,7 +906,7 @@ case "$TGT_RES" in
     # SVCD
     "SVCD" )
         TGT_WIDTH="480"
-        if test x"$TVSYS" = x"PAL"; then
+        if test "$TVSYS" = "PAL"; then
             TGT_HEIGHT="576"
         else
             TGT_HEIGHT="480"
@@ -899,7 +925,7 @@ case "$TGT_RES" in
     # Half-D1 DVD
     "Half-DVD" )
         TGT_WIDTH="352"
-        if test x"$TVSYS" = x"PAL"; then
+        if test "$TVSYS" = "PAL"; then
             TGT_HEIGHT="576"
         else
             TGT_HEIGHT="480"
@@ -924,7 +950,7 @@ case "$TGT_RES" in
         fi
 
         # PAL or NTSC
-        if test x"$TVSYS" = x"PAL"; then
+        if test "$TVSYS" = "PAL"; then
             TGT_HEIGHT="576"
         else
             TGT_HEIGHT="480"
@@ -936,7 +962,7 @@ case "$TGT_RES" in
         : ${VID_BITRATE:=$DEFAULT_BR}
 
         # Use optimal (non-standard!) GOP size for live video
-        if test x"$VIDEO_TYPE" = x"live"; then
+        if test "$VIDEO_TYPE" = "live"; then
             GOP_MAXSIZE="24"
         fi
         # KVCDx3(a) is treated as SVCD, since the standard doesn't specify
@@ -950,7 +976,7 @@ case "$TGT_RES" in
     # DVD (and KDVD/BDVD)
     "DVD" | "KDVD" | "BDVD" )
         TGT_WIDTH="720"
-        if test x"$TVSYS" = x"PAL"; then
+        if test "$TVSYS" = "PAL"; then
             TGT_HEIGHT="576"
         else
             TGT_HEIGHT="480"
@@ -1053,7 +1079,7 @@ QUANT=$(expr 13 \- $VID_QUALITY)
 
 # mpeg2enc encoding quality options
 # Don't use -q for VCD (since -q implies variable bitrate)
-if test x"$TGT_RES" = x"VCD"; then
+if test "$TGT_RES" = "VCD"; then
     MPEG2_QUALITY="--reduction-4x4 2 --reduction-2x2 1"
     FF_QUANT=""
 else
@@ -1124,10 +1150,9 @@ yecho
 
 
 # Probe for width, height, frame rate, and duration
-# Do not probe inputs that are not files
-if test x"$IN_FILE_TYPE" = x"file"; then
+# (only for locally-accessible infiles, not URI-addressed infiles)
+if test "$IN_FILE_TYPE" = "file"; then
 
-    # Probe $IN_FILE for resolution, fps, and length.
     yecho "Probing video for information. This may take several minutes..."
 
     # Get an MD5sum of the input file for statistics
@@ -1145,8 +1170,9 @@ if test x"$IN_FILE_TYPE" = x"file"; then
     V_DVD_OK=false
     V_RES=""
     
-    # Sneaky but simple way to set some variables via 'idvid'.
-    # Exit on failure.
+    # Override the above A_ and V_ variables by 'eval'ing the output of
+    # 'idvid -terse' on the infile. Exit on failure.
+    # (Yes, I know eval==evil. Deal.)
     if eval $(idvid -terse "$IN_FILE"); then :; else
         runtime_error "Could not identify source video: $IN_FILE"
     fi
@@ -1158,29 +1184,29 @@ if test x"$IN_FILE_TYPE" = x"file"; then
         echo "It doesn't look like you have enough space to encode this video."
         echo "Of course, I could be wrong. Do you want to proceed anyway? (y/n)"
         read PROCEED
-        if test x"$PROCEED" != x"y"; then
+        if test "$PROCEED" != "y"; then
             cleanup
             exit 0
         fi
     fi
 
     # Check for compliance in existing video
-    if test x"$TGT_RES" = x"VCD"; then
+    if test "$TGT_RES" = "VCD"; then
         $A_VCD1_OK || $A_VCD2_OK && AUDIO_OK=:
         $V_VCD_OK && test "$V_RES" = "${BASETVSYS}_VCD" && VIDEO_OK=:
         
-    elif test x"$TGT_RES" = x"SVCD"; then
+    elif test "$TGT_RES" = "SVCD"; then
         $A_SVCD_OK && AUDIO_OK=:
         $V_SVCD_OK && test "$V_RES" = "${BASETVSYS}_SVCD" && VIDEO_OK=:
 
     else # Any DVD format
         $A_DVD_OK && AUDIO_OK=:
         if $V_DVD_OK; then
-            if test x"$TGT_RES" = x"DVD-VCD"; then
+            if test "$TGT_RES" = "DVD-VCD"; then
                 test "$V_RES" = "${BASETVSYS}_VCD" && VIDEO_OK=:
-            elif test x"$TGT_RES" = x"Half-DVD"; then
+            elif test "$TGT_RES" = "Half-DVD"; then
                 test "$V_RES" = "${BASETVSYS}_HALF" && VIDEO_OK=:
-            elif test x"$TGT_RES" = x"DVD"; then
+            elif test "$TGT_RES" = "DVD"; then
                 test "$V_RES" = "${BASETVSYS}_DVD" && VIDEO_OK=:
             fi
         fi
@@ -1315,7 +1341,7 @@ fi
 
 # Correct wmv 1000fps videos
 if $FORCE_FPS; then :
-elif test x"$ID_VIDEO_FPS" = "x1000.000"; then
+elif test "$ID_VIDEO_FPS" = "1000.000"; then
     FORCE_FPS=:
     FORCE_FPSRATIO=$TGT_FPSRATIO
     yecho "Found 1000fps (wmv) source, setting input to $TGT_FPS fps."
@@ -1331,7 +1357,7 @@ if $FORCE_FPS; then
     yecho "Forcing input to be treated as $FORCE_FPSRATIO fps."
     ADJUST_FPS="yuvfps -s $FORCE_FPSRATIO -r $TGT_FPSRATIO $VERBOSE |"
 # If FPS is already at the target rate, leave it alone
-elif test x"$ID_VIDEO_FPS" = x"$TGT_FPS"; then
+elif test "$ID_VIDEO_FPS" = "$TGT_FPS"; then
     yecho "Input is already $TGT_FPS fps. Framerate will not be altered."
     ADJUST_FPS=""
 else
@@ -1354,7 +1380,7 @@ fi
 
 # Tell mplayer and mpeg2enc to do interlaced encoding, if requested
 # (except for VCD, which doesn't support it)
-if $INTERLACED && test x"$TGT_RES" != x"VCD"; then
+if $INTERLACED && test "$TGT_RES" != "VCD"; then
 
     # Unneeded, and possibly harmful?
     # MPEG2_FMT="$MPEG2_FMT --interlace-mode 1"
@@ -1443,8 +1469,8 @@ if $PARALLEL && $DO_NORM; then
 fi
 
 if $PARALLEL; then
-    rm -f "$OUT_PREFIX.$AUD_SUF"
-    mkfifo "$OUT_PREFIX.$AUD_SUF"
+    rm -f "$AUDIO_STREAM"
+    mkfifo "$AUDIO_STREAM"
 fi
 
 
@@ -1453,14 +1479,14 @@ if ! $FORCE_ENCODING && $AUDIO_OK; then
     yecho "Found compliant audio and dumping the stream."
     precho "This sometimes causes errors when multiplexing; add '-force' to the tovid command line to re-encode if multiplexing fails."
     yecho "Copying the existing audio stream with the following command:"
-    AUDIO_CMD="$PRIORITY mplayer $MPLAYER_OPTS \"$IN_FILE\" -dumpaudio -dumpfile \"$OUT_PREFIX.$AUD_SUF\""
+    AUDIO_CMD="$PRIORITY mplayer $MPLAYER_OPTS \"$IN_FILE\" -dumpaudio -dumpfile \"$AUDIO_STREAM\""
     yecho "$AUDIO_CMD"
     cmd_exec "$AUDIO_CMD"
 
     if $FAKE || $PARALLEL; then
         :
     else
-        file_output_progress "$OUT_PREFIX.$AUD_SUF" "Copying compliant audio stream"
+        file_output_progress "$AUDIO_STREAM" "Copying compliant audio stream"
         wait
     fi
 
@@ -1511,7 +1537,7 @@ else
         yecho "Encoding audio stream to $AUD_SUF with the following command:"
     fi
     AUDIO_ENC="$AUDIO_ENC -vn -ab $AUD_BITRATE -ar $SAMPRATE -ac 2"
-    AUDIO_ENC="$AUDIO_ENC -acodec $AUD_SUF -y \"$OUT_PREFIX.$AUD_SUF\""
+    AUDIO_ENC="$AUDIO_ENC -acodec $AUD_SUF -y \"$AUDIO_STREAM\""
     yecho "$AUDIO_ENC"
     cmd_exec "$AUDIO_ENC"
 
@@ -1521,10 +1547,10 @@ else
     # If not in parallel mode, show output progress
     # and wait for successful completion
     else
-        file_output_progress "$OUT_PREFIX.$AUD_SUF" "Encoding audio to $AUD_SUF"
+        file_output_progress "$AUDIO_STREAM" "Encoding audio to $AUD_SUF"
         wait
 
-        if test -f "$OUT_PREFIX.$AUD_SUF"; then
+        if test -f "$AUDIO_STREAM"; then
             yecho "Audio encoding finished successfully."
         else
             runtime_error "There was a problem with encoding the audio to $AUD_SUF format."
@@ -1542,14 +1568,14 @@ yecho
 # Remove stream.yuv
 rm -f stream.yuv
 if $PARALLEL; then
-    rm -f "$OUT_PREFIX.$VID_SUF"
-    mkfifo "$OUT_PREFIX.$VID_SUF"
+    rm -f "$VIDEO_STREAM"
+    mkfifo "$VIDEO_STREAM"
 fi
 
 # If existing video is OK, skip video encoding and just copy the stream
 if ! $FORCE_ENCODING && $VIDEO_OK; then
     yecho "Copying existing video stream with the following command:"
-    VID_COPY_CMD="mencoder -of rawvideo -nosound -ovc copy \"$IN_FILE\" -o \"$OUT_PREFIX.$VID_SUF\""
+    VID_COPY_CMD="mencoder -of rawvideo -nosound -ovc copy \"$IN_FILE\" -o \"$VIDEO_STREAM\""
     yecho "$VID_COPY_CMD"
 
 
@@ -1560,7 +1586,7 @@ if ! $FORCE_ENCODING && $VIDEO_OK; then
     if $FAKE || $PARALLEL; then
         :
     else
-        file_output_progress "$OUT_PREFIX.$VID_SUF" "Copying existing video stream"
+        file_output_progress "$VIDEO_STREAM" "Copying existing video stream"
         wait
     fi
 else
@@ -1571,7 +1597,7 @@ else
         mkfifo stream.yuv
     fi
     VID_PLAY_CMD="$PRIORITY $MPLAYER -benchmark -nosound -noframedrop $SUBTITLES -vo yuv4mpeg${YUV4MPEG_ILACE} ${VF_PRE} ${VID_FILTER} ${VID_SCALE} ${VF_POST} \"$IN_FILE\" $MPLAYER_OPTS"
-    VID_ENC_CMD="cat stream.yuv | $YUVDENOISE $ADJUST_FPS $PRIORITY mpeg2enc --sequence-length $DISC_SIZE --nonvideo-bitrate $NONVIDEO_BITRATE $MTHREAD $ASPECT_FMT $MPEG2_FMT $VID_FPS $VERBOSE $VID_NORM $MPEG2_QUALITY -o \"$OUT_PREFIX.$VID_SUF\""
+    VID_ENC_CMD="cat stream.yuv | $YUVDENOISE $ADJUST_FPS $PRIORITY mpeg2enc --sequence-length $DISC_SIZE --nonvideo-bitrate $NONVIDEO_BITRATE $MTHREAD $ASPECT_FMT $MPEG2_FMT $VID_FPS $VERBOSE $VID_NORM $MPEG2_QUALITY -o \"$VIDEO_STREAM\""
     yecho $VID_PLAY_CMD
     yecho $VID_ENC_CMD
     # Start encoding
@@ -1593,7 +1619,7 @@ else
         :
     # Show progress report while video is encoded
     else
-        file_output_progress "$OUT_PREFIX.$VID_SUF" "Encoding video stream"
+        file_output_progress "$VIDEO_STREAM" "Encoding video stream"
         wait
         :
     fi
@@ -1606,9 +1632,9 @@ yecho
 if $FAKE || $PARALLEL; then
     :
 else
-    test ! -f "$OUT_PREFIX.$AUD_SUF" && \
+    test ! -f "$AUDIO_STREAM" && \
         runtime_error "The audio stream did not encode properly, and no output file exists."
-    test ! -f "$OUT_PREFIX.$VID_SUF" && \
+    test ! -f "$VIDEO_STREAM" && \
         runtime_error "The video stream did not encode properly, and no output file exists."
 fi
 
@@ -1623,8 +1649,8 @@ fi
 # ******************************************************************************
 # ******************************************************************************
 
-AUDIO_SIZE=$(du -c -b "$OUT_PREFIX.$AUD_SUF" | awk 'END{print $1}')
-VIDEO_SIZE=$(du -c -b "$OUT_PREFIX.$VID_SUF" | awk 'END{print $1}')
+AUDIO_SIZE=$(du -c -b "$AUDIO_STREAM" | awk 'END{print $1}')
+VIDEO_SIZE=$(du -c -b "$VIDEO_STREAM" | awk 'END{print $1}')
 # Total size of streams so far (in MBytes)
 STREAM_SIZE=$(expr \( $AUDIO_SIZE \+ $VIDEO_SIZE \) \/ 1000000)
 # If it will exceed disc size, add '%d' field to allow mplex to split the output
@@ -1633,7 +1659,7 @@ if test $STREAM_SIZE -gt $DISC_SIZE; then
 fi
 
 
-MPLEX_CMD="mplex $MUX_OPTS -o \"$OUT_FILENAME\" \"$OUT_PREFIX.$VID_SUF\" \"$OUT_PREFIX.$AUD_SUF\""
+MPLEX_CMD="mplex $MUX_OPTS -o \"$OUT_FILENAME\" \"$VIDEO_STREAM\" \"$AUDIO_STREAM\""
 yecho "Multiplexing audio and video together with the following command:"
 yecho $MPLEX_CMD
 
