Fix 'Usage' line to use new COMMAND SCRIPT syntax. Error message if tovid-init not found.

diff --git a/trunk/tovid/src/idvid b/trunk/tovid/src/idvid
--- a/trunk/tovid/src/idvid
+++ b/trunk/tovid/src/idvid
@@ -2,7 +2,12 @@
 #set -u
 
 ME="[idvid]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run idvid as:\ntovid id OPTIONS"
+exit 1 ; }
 
 # idvid
 # Part of the tovid suite
@@ -41,7 +46,7 @@ $TOVID_HOME_PAGE
 EOF`
 
 USAGE=`cat << EOF
-Usage: idvid [OPTIONS] <file list>
+Usage: tovid id [OPTIONS] <file list>
 
 Where OPTIONS may be any of the following:
 
diff --git a/trunk/tovid/src/postproc b/trunk/tovid/src/postproc
--- a/trunk/tovid/src/postproc
+++ b/trunk/tovid/src/postproc
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 ME="[postproc]:"
-. tovid-init
+. tovid-init 2>/dev/null ||
+{ echo -e "===============================================================\n"
+echo -e "'tovid-init' not found.  Was tovid improperly installed?"
+echo -e "Or are you trying to run the script directly?"
+echo -e "Please run postproc as:\ntovid postproc OPTIONS"
+exit 1 ; }
 
 # postproc
 # Part of the tovid suite
@@ -40,7 +45,7 @@ $TOVID_HOME_PAGE
 EOF`
 
 USAGE=`cat << EOF
-Usage: postproc [OPTIONS] {input file} {output file}
+Usage: tovid postproc [OPTIONS] {input file} {output file}
 
 Where OPTIONS may be any of the following:
 
