smarter bootstrap -- will not use old automake versions

diff --git a/trunk/tovid/bootstrap b/trunk/tovid/bootstrap
--- a/trunk/tovid/bootstrap
+++ b/trunk/tovid/bootstrap
@@ -1,9 +1,6 @@
-#! /bin/sh
+#!/bin/bash
 
 # Call this script after editing configure.ac or Makefile.am
-# then:
-# $ ./configure
-# $ ./setup.sh
 
 # Copyright (C) 2005 Joe Friedrichsen <friedrij@users.berlios.de>
 # 
@@ -22,14 +19,48 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
-[ -e Makefile ] && make distclean
+# Test for good automake -- the no AM_PYTHON error
+# tovid needs automake 1.10
+AM_VERSION=$(automake --version | head -n 1 | sed 's/[a-zA-Z ()]//g')
+AM_110=$(type -a automake-1.10 2>>/dev/null | awk '{print $3}')
 
+if test $AM_VERSION == "1.10"; then
+    AUTOMAKE=automake
+elif test -n $AM_110; then
+    AUTOMAKE=automake-1.10
+else
+    echo "I couldn't find automake-1.10 on your system. Is it installed?"
+    echo "I need automake-1.10 to generate ./configure..."
+    echo "Exiting..."
+    exit 1
+fi
+
+# See if tovid has been installed previously
+if test -e Makefile; then
+    echo "I found a Makefile! This may mean you have a previous version"
+    echo "of tovid installed. Old tovid installations can cause strange"
+    echo "and frustrating behavior. Do you want to uninstall it before"
+    echo "continuing?"
+    echo 
+    echo -n "  Uninstall tovid? [y/N] "
+    
+    ANSWER=n
+    read ANSWER
+    
+    if test $ANSWER == "y" || test $ANSWER == "Y"; then
+        echo -n "  Enter your root "
+        su -c "make uninstall"
+    fi      
+    
+    make distclean
+fi
+
+# Clean out old autotools-genreated files
 rm -rvf "autom4te.cache"
-rm -rvf aclocal.m4 config.log config.status configure \
-        Makefile Makefile.in
+rm -rvf aclocal.m4 config.log config.status configure Makefile Makefile.in
 
 if aclocal \
-   && automake --gnu --add-missing \
+   && $AUTOMAKE --gnu --add-missing \
    && autoconf
 then
    echo
